# debug config
name: mega-backuper-example

services:

  postgres-example:
    image: postgres:alpine
    container_name: postgres-example
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mega-backuper:
    build:
      context: .
    container_name: mega-backuper
    restart: unless-stopped
    volumes:
      - ./backuper_test.json:/app/backuper.json

volumes:
  postgres:
