# debug config
name: mega-backuper-example

services:

  nginx-example:
    image: nginx:alpine
    container_name: nginx-example
    volumes:
      - nginx:/usr/share/nginx/html
    # restart: always

  postgres-example:
    image: postgres:18
    container_name: postgres-example
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql
    # restart: always
  
  timescaledb-example:
    image: timescale/timescaledb:latest-pg18
    container_name: timescaledb-example
    environment:
      - POSTGRES_DB=timescaledb
      - POSTGRES_USER=timescaledb
      - POSTGRES_PASSWORD=timescaledb
      - PGDATA=/pgdata
    volumes:
      - timescaledb_data:/pgdata
    # restart: always
  
  mariadb-example:
    image: mariadb:12
    container_name: mariadb-example
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=mariadb
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=mariadb
    volumes:
      - mariadb:/var/lib/mysql
    # restart: always
  
  mysql-example:
    container_name: mysql-example
    image: mysql:9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - mysql:/var/lib/mysql
    # restart: always

  mega-backuper:
    build:
      context: .
    container_name: mega-backuper
    volumes:
      - ./backuper_test.json:/app/backuper.json
      - nginx:/tmp/nginx
    # restart: always

volumes:
  nginx:
  postgres:
  timescaledb_data:
  mariadb:
  mysql:
