name: mega-backuper-example

services:

  postgres-example:
    image: postgres:alpine
    container_name: postgres-example
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  mega-backuper:
    image: ghcr.io/jsfraz/mega-backuper:latest
    container_name: mega-backuper
    restart: always
    volumes:
      # TODO actually replace with actual config file
      # - ./backuper.json:/app/backuper.json   # backuper settings
      - ./backuper_test.json:/app/backuper.json

volumes:
  postgres:
