name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}:latest
